# Generated by Django 3.1.4 on 2020-12-04 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Okul Adı')),
                ('type', models.IntegerField(choices=[(0, 'İlkokul'), (1, 'İlkögretim'), (2, 'Lise'), (3, 'Meslek Okulu'), (4, 'Lisans'), (5, 'Yüksek Lisans')], default=0, verbose_name='Eğitim Seviyesi')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('birth_date', models.DateField(verbose_name='Doğum Tarihi')),
                ('tc_number', models.BigIntegerField(verbose_name='Tc. No')),
                ('gender', models.IntegerField(choices=[(0, 'Bay'), (1, 'Bayan')], default=0, verbose_name='Cinsiyet')),
                ('approval', models.BooleanField(default=True, verbose_name='Sözleşmeyi Onaylıyorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.school', verbose_name='Okul')),
            ],
        ),
    ]
