# Generated by Django 3.1.4 on 2020-12-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Erkek'), (1, 'Kız')], default=0, verbose_name='Cinsiyet'),
        ),
    ]
